#! /usr/bin/env bash
docker build -t az .
echo "
-----------------------------------------------------------------------
This opens a docker container connected to the current directory.

Once docker has connected, run:

cd /opt/az-ml-qs
az login

and then try out the example command line:

./Start-OnComputeTarget.ps1 ml1 ml1 ml1 ml1 -location uksouth \`
        -environmentFor PyTorch  \`
        -submit \`
        -NoConfirm

and/or

./Start-OnComputeTarget.ps1 -? | less
-----------------------------------------------------------------------
"
docker run --rm -it -v $(pwd):/opt/az-ml-qs az pwsh -interactive -NoExit -command "cd /opt/az-ml-qs"

# fish:
# docker run --rm -it -v (pwd):/opt/az-ml-qs az pwsh -interactive -NoExit -command "cd /opt/az-ml-qs"